# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demographics',
            new_name='Demographic',
        ),
    ]
