# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0002_auto_20171210_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='city',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='info',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='state',
        ),
        migrations.AddField(
            model_name='helpee',
            name='info',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helper',
            name='money',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='helper',
            name='travel',
            field=models.NullBooleanField(),
        ),
    ]
