# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0003_auto_20171210_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='city',
            field=models.CharField(default='N/A', max_length=60),
        ),
        migrations.AddField(
            model_name='helper',
            name='state',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
