# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0004_auto_20171210_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='helper',
            name='money',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='helper',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='helper',
            name='travel',
            field=models.BooleanField(),
        ),
    ]
