# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicSite', '0004_auto_20171210_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('t', 'travel'), ('m', 'money')], max_length=1)),
                ('estimated_dollars', models.IntegerField()),
                ('helpee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_helpee', to=settings.AUTH_USER_MODEL)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_helper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('details', models.TextField()),
                ('dollars', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicSite.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='helper',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='helper',
            name='money',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helper',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='helper',
            name='travel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
