# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0005_auto_20171210_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpee',
            name='info',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='helpee',
            name='money',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='helpee',
            name='travel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='helper',
            name='money',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='helper',
            name='travel',
            field=models.NullBooleanField(),
        ),
    ]
