# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0007_auto_20171210_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='helpee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicSite.Helpee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicSite.Helper'),
        ),
    ]
