# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0007_auto_20171210_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='money',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helper',
            name='travel',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
