# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0008_auto_20171210_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpee',
            name='amount_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helper',
            name='amount_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
