# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0009_auto_20171210_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpee',
            name='travel_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
