# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0009_auto_20171210_1937'),
        ('publicSite', '0008_auto_20171210_1939'),
    ]

    operations = [
    ]
