# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicSite', '0010_merge_20171210_2020'),
        ('publicSite', '0010_helpee_travel_cost'),
    ]

    operations = [
    ]
